/** Temporary local copy. The integration owner will move these keys to strings.ts. */
export const requestTraceCopy = {
  title: "网络诊断瀑布图",
  subtitle: "精确测量真实诊断请求在各阶段的时延分布（DNS / 握手 / TLS / 响应）",
  badgeDiagnostic: "类型：主动诊断测试 · 不解密用户日常流量",
  source: "主动诊断记录",
  target: "诊断目标",
  route: "诊断链路",
  routeFilter: "筛选链路",
  outcomeFilter: "筛选结果",
  all: "全部",
  modeDirect: "直连链路",
  modeProxy: "当前代理链路",
  runAction: "发起诊断测试",
  testing: "正在测试各阶段时延…",
  refresh: "刷新诊断记录",
  loading: "正在读取诊断记录",
  stale: "上次诊断记录（读取失败）",
  explicitOnly:
    "仅点击后向固定目标发送一次请求；不自动探测，不解密日常 HTTPS 流量。",
  limits: "最长 10 秒 · 最多读取 64 KiB · 同时 1 次 · 保留最近 64 条",
  emptyTitle: "暂未执行网络诊断",
  emptyDetail:
    "点击“发起诊断测试”即可测量当前网络直连与代理节点的各阶段实际耗时。",
  noMatches: "没有符合筛选条件的诊断记录",
  phaseDetail: "查看详细阶段耗时",
  records: "条诊断记录",
  unknown: "未知",
  notObserved: "未观测",
  observed: "已观测",
  incomplete: "已开始，未完成",
  notProvided: "未提供",
  notObservedReason: "未取得此阶段的测量数据",
  peerOrigin: "目标服务地址",
  peerProxy: "代理监听器地址",
  currentPolicy:
    "当前代理链路使用已接受的混合监听配置；其策略可能选择直连，不保证经过远端节点。",
  proxyTCP: "代理连接 (TCP)",
  originTLS: "目标服务 TLS 握手",
  multipleTCP: "TCP 连接跨度（多次尝试）",
  multipleProxyTCP: "代理连接跨度 (TCP，多次尝试)",
  phaseScope:
    "代理链路：代理侧 DNS 未暴露，本地不可观测；TCP 测量到代理监听器；CONNECT 仅在可观测时展示。TLS 测量目标服务验证握手；代理节点内部 TLS 不可观测。DNS 服务器未提供。",
  offsetHint:
    "阶段使用各自的真实开始/结束偏移，可能重叠；未知不等于 0。菱形标记表示终止位置。",
  chartLabel:
    "真实主动诊断请求阶段瀑布图：横轴为相对请求开始的毫秒偏移；空心圆表示未完成阶段；菱形表示失败或终止",
  failureMarker: "失败或终止",
  demoFictional: "虚构演示样本，不代表真实请求或日常 HTTPS 流量",
  demoTitle: "网络诊断瀑布图 · 演示",
  demoSubtitle: "虚构请求阶段 · 相对开始时间",
  demoHint: "虚构固定样本 · 拖动底部范围缩放 · 悬停查看阶段耗时",
  phases: {
    dns: "DNS 解析",
    tcp: "TCP 握手",
    connect: "CONNECT 隧道",
    tls: "TLS 握手",
    ttfb: "首字等待 (TTFB)",
    transfer: "内容传输",
  },
  outcomes: {
    success: "成功",
    http_error: "HTTP 错误",
    failed: "失败",
    cancelled: "已取消",
    timeout: "超时",
  },
  columns: {
    trace: "诊断目标 / 时间",
    route: "链路",
    outcome: "结果",
    phase: "阶段",
    observation: "观测状态",
    start: "开始偏移 / ms",
    end: "结束偏移 / ms",
    duration: "阶段耗时 / ms",
    total: "总耗时 / ms",
    reason: "原因 / 失败阶段",
    peer: "对端地址 / 范围",
    status: "HTTP 状态码",
    bytes: "读取字节",
    bodyLimit: "已到读取上限",
  },
  yes: "是",
  no: "否",
  reasons: {
    not_observed: "未取得此阶段的测量数据",
    not_used_by_direct_route: "直连链路不使用 CONNECT 隧道",
    proxy_origin_dns_not_observable: "代理侧目标 DNS 未暴露，本地不可观测",
    connect_timing_not_exposed_by_httptrace: "HTTP 追踪未提供 CONNECT 阶段时间",
    multiple_connection_attempt_span:
      "此跨度包含多次连接尝试，不可与其他阶段简单相加",
  },
} as const;
